name: Advance

# on: push
on: pull_request

jobs:
  simple-node-job:
    runs-on: ubuntu-latest
    steps:
      - name: Log Node version
        run: node -v

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 7

      - name: Log the Updated version
        run: node -v

  matrix-job:
    strategy:
      matrix:
        # any key name
        node_version: [8, 10]
        # a key for OS
        # os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
        exclude:
          - os: ubuntu-latest
            node: 8
      # default true, if one fails no one else runs
      fail-fast: true
      # by default github will try to maximize it
      max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log Node version
        run: node -v

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version}}

      - name: Log the Updated version
        run: node -v
