name: Docker Test

# on: push
on: pull_request

jobs:
  docker-test:
    runs-on: ubuntu-latest
    # container: node:13.5.0-alpine3.10
    container:
      image: node:13.5.0-alpine3.10
    steps:
      - name: Log Container Node version
        run: |
          node -v
          cat /etc/os-release
